### PR TITLE
Ionic 2 Demo

### PR DESCRIPTION
**Pull request by twinj**
Includes custom config plugin to handle requirements for Info.plist and cocoa pods plugin to handle fetching the framework. Requires a valid licence.

Also makes use of the Ionic WKWebView plugin, this will not work until PR 24 is merged. This plugin can be removed from the config.xml, however it will become Ionic 2s standard.

### CODE REVIEW

**Comment by juliangrosshauser** [comment]
Thank you for your contribution @twinj! :tada:
We don't have any experience with Ionic yet, so this PR is very helpful.

I started a step-by-step guide for Ionic 2, so people can start from scratch (native file plugin is still missing etc.): https://github.com/PSPDFKit/Cordova-iOS/blob/julian/ionic2/README.md#ionic-2

I'm not using the CocoaPods plugin, but integrating the PSPDFKit framework manually instead (because this is what we currently recommend for Cordova). After adding `PSPDFKit.framework` to the embedded frameworks section in the Xcode project and adjusting the deployment target to 9.0 I can build the app from within Xcode, which is expected. But running `ionic run ios` from the command line leads to the following errors:

```
While building module 'PSPDFKit' imported from /Users/julian/dev/Cordova-iOS/Ionic2Demo/platforms/ios/Ionic2Demo/Plugins/com.pspdfkit.cordovaplugin/PSPDFKitPlugin.m:15:
In file included from <module-includes>:1:
In file included from /Users/julian/dev/Cordova-iOS/Ionic2Demo/platforms/ios/PSPDFKit.framework/Headers/PSPDFKit.h:19:
In file included from /Users/julian/dev/Cordova-iOS/Ionic2Demo/platforms/ios/PSPDFKit.framework/Headers/PSPDFModelUmbrella.h:17:
/Users/julian/dev/Cordova-iOS/Ionic2Demo/platforms/ios/PSPDFKit.framework/Headers/PSPDFVersion.h:16:2: error: PSPDFKit 6 supports iOS 9.0 upwards.
#error PSPDFKit 6 supports iOS 9.0 upwards.
 ^
1 error generated.
/Users/julian/dev/Cordova-iOS/Ionic2Demo/platforms/ios/Ionic2Demo/Plugins/com.pspdfkit.cordovaplugin/PSPDFKitPlugin.m:15:9: fatal error: could not build module 'PSPDFKit'
#import <PSPDFKit/PSPDFKit.h>
 ~~~~~~~^
2 errors generated.
```

I don't get these errors when integrating our plugin into a Cordova project, after editing the Xcode project. Adding `<preference name="deployment-target" value="9.0" />` to `config.xml` also doesn't get rid of the deployment target error.

Do you know by any chance why I get these errors when building the app from the command line?

I use the following versions:

```
Cordova CLI: 6.5.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.10.2
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by twinj** [comment]
When first adding the framework for my project i ran into a few hiccups such as this. It's the reason why I added the PR. 

Perhaps you could try a cordova clean, if that fails you might have to remove the ios platform and re add it to the project while also re adding the framework. It's still basically cordova under the covers. 

In the meantime I'll start a blank ionic project from scratch and add the framework as you have to see if i can recreate the issue. And get back to you from there.

**Comment by twinj** [comment]
On a side note adding the framework this way isn't best practice. Declaring the var in the typescript typings file is also the second best option. The best practice is to create a native plugin wrapper from Ionic-native.

The advantage of doing it this way is that it can be easily mocked for testing and running in a browser. Any direct reference to the plugin is through this instead of the PSPDFKitPlugin var. I created one for my project. You add it to an Ionic project by declaring it in the app module as you would any other native plugin. You can than inject it into any Ionic component constructor. 

I have tested this and it works extremely well. I am using the below unfinished version and add the code for each method when the need arises. I understand it's quite a bit more code to maintain if you go down this route. Ionic users will certainly appreciate it.
`

    import { Injectable } from '@angular/core';
    import { Plugin, Cordova } from '@ionic-native/core';

    @Plugin({
        pluginName: 'PSPDFKit',
        plugin: 'com.pspdfkit.cordovaplugin',
        pluginRef: 'PSPDFKitPlugin',
        repo: 'https://github.com/PSPDFKit/Cordova-iOS'
    })
    @Injectable()
    export class PSPDFKit {

        @Cordova()
        setLicenseKey(key: string) { ; }

        @Cordova()
        present(path: string, options: any, callback?: any) {}
    }

`

**Comment by twinj** [comment]
Please keep this open so others can at least look at it as a resource.

**Comment by juliangrosshauser** [comment]
@twinj: I'm really sorry that it took me so long to respond here. We have no intention of closing your pull request.

I just finished the install instructions for Ionic 3: https://github.com/PSPDFKit/Cordova-iOS/tree/julian/ionic#ionic
Works without any problems.

We'll test the performance on a few devices on Monday. If everything works well we'll merge your PR, update the demo app to Ionic 3 and also add the install instructions.

**Comment by twinj** [comment]
This is now behind in Ionic version but should still work with Ionic 3. Ionic 3 is basically Ionic 2 + Lazy loading. It's still called Ionic 2 but has a version 3.1.0 - kind of throws you off.

**Comment by juliangrosshauser** [comment]
Testing went well, everything is running without problems.
We'll merge this PR and update the demo to Ionic 3.

@twinj: Thank you for your contribution and sorry again that this took so long.

**Pull request merged**
